openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/usuarios/:
    get:
      operationId: api_usuarios_list
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
          description: ''
    post:
      operationId: api_usuarios_create
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usuario'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
  /api/usuarios/{id}/:
    get:
      operationId: api_usuarios_retrieve
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
    put:
      operationId: api_usuarios_update
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usuario'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
    patch:
      operationId: api_usuarios_partial_update
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUsuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUsuario'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUsuario'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
    delete:
      operationId: api_usuarios_destroy
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /usuarios/:
    get:
      operationId: usuarios_list
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      tags:
      - usuarios
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
          description: ''
    post:
      operationId: usuarios_create
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      tags:
      - usuarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usuario'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
  /usuarios/{id}/:
    get:
      operationId: usuarios_retrieve
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - usuarios
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
    put:
      operationId: usuarios_update
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - usuarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usuario'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
    patch:
      operationId: usuarios_partial_update
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - usuarios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUsuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUsuario'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUsuario'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: ''
    delete:
      operationId: usuarios_destroy
      description: API para gestionar usuarios. Permite operaciones CRUD (Crear, Leer,
        Actualizar, Eliminar).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this usuario.
        required: true
      tags:
      - usuarios
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedUsuario:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nombre:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        fecha_creacion:
          type: string
          format: date-time
          readOnly: true
    Usuario:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nombre:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        fecha_creacion:
          type: string
          format: date-time
          readOnly: true
      required:
      - email
      - fecha_creacion
      - id
      - nombre
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
